# FORESIGHT
## Data Loading & Validation

This notebook loads and validates the four core FORESIGHT datasets:

1. Product Master
2. Sales
3. Inventory
4. Calendar

Objectives:
- Loads all datastes
- Inspect dimensions and columns    
- Check data types
- Check missing values
- Check duplicates
- Validate data ranges
- Validate SKU relationships
- Validate sales and inventory coverage

# Import Libraries

In [3]:
import pandas as pd
import numpy as np 
from pathlib import Path
import warnings

warnings.filterwarnings("ignore")

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 120)

print("Libraries imported successfully")

Libraries imported successfully

# Define Project Root

In [6]:
# Project root
PROJECT_ROOT = Path.cwd().parent

# Data folders
RAW_DATA_PATH = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA_PATH = PROJECT_ROOT / "data" / "processed"

print("Project Root :", PROJECT_ROOT)
print("Raw Data     :", RAW_DATA_PATH)
print("Processed    :", PROCESSED_DATA_PATH)

Project Root : d:\Zidio project\FORESIGHT Project
Raw Data     : d:\Zidio project\FORESIGHT Project\data\raw
Processed    : d:\Zidio project\FORESIGHT Project\data\processed

# Check Raw Data Folder

In [7]:
if not RAW_DATA_PATH.exists():
    raise FileNotFoundError(f"Raw data folder not found at {RAW_DATA_PATH}. Please ensure the raw data is placed in the correct directory.")
print("Raw data folder exists.\n")

print("Files Available:")
for file in RAW_DATA_PATH.iterdir():
    print(" -",file.name)

Raw data folder exists.

Files Available:
 - calendar.csv
 - inventory.csv
 - product_master.csv
 - sales.csv

# Define Datasets Files

In [8]:
PRODUCT_FILE = RAW_DATA_PATH / "product_features.csv"
SALES_FILE = RAW_DATA_PATH / "sales_data.csv"
INVENTORY_FILE = RAW_DATA_PATH / "inventory_data.csv"
CALENDAR_FILE = RAW_DATA_PATH / "calendar_data.csv"

files = {
    "Product Features": PRODUCT_FILE,
    "Sales Data": SALES_FILE,
    "Inventory Data": INVENTORY_FILE,
    "Calendar Data": CALENDAR_FILE
}

for name, path in files.items():
    print(f"{name:15} -> {path}")

Product Features -> d:\Zidio project\FORESIGHT Project\data\raw\product_features.csv
Sales Data      -> d:\Zidio project\FORESIGHT Project\data\raw\sales_data.csv
Inventory Data  -> d:\Zidio project\FORESIGHT Project\data\raw\inventory_data.csv
Calendar Data   -> d:\Zidio project\FORESIGHT Project\data\raw\calendar_data.csv

# Verify All files exists

In [18]:
# Cell 6: Validate required datasets

from pathlib import Path

# Project root
PROJECT_ROOT = Path.cwd().parent

# Raw data directory
DATA_DIR = PROJECT_ROOT / "Data" / "raw"

# Required dataset files
files = {
    "Sales": DATA_DIR / "sales.csv",
    "Inventory": DATA_DIR / "inventory.csv",
    "Products": DATA_DIR / "product_master.csv",
    "Calendar": DATA_DIR / "calendar.csv"
}

# Check for missing files
missing_files = []

for name, path in files.items():
    if not path.exists():
        missing_files.append(f"{name}: {path}")

# Validate files
if missing_files:
    print("❌ Missing files:")
    
    for file in missing_files:
        print(" -", file)
    
    raise FileNotFoundError(
        "One or more required datasets are missing."
    )

print("✅ All four required datasets are present.")

# Display paths
print("\nDataset paths:")
for name, path in files.items():
    print(f" - {name}: {path}")

✅ All four required datasets are present.

Dataset paths:
 - Sales: d:\Zidio project\FORESIGHT Project\Data\raw\sales.csv
 - Inventory: d:\Zidio project\FORESIGHT Project\Data\raw\inventory.csv
 - Products: d:\Zidio project\FORESIGHT Project\Data\raw\product_master.csv
 - Calendar: d:\Zidio project\FORESIGHT Project\Data\raw\calendar.csv

# Load All Datasets

In [19]:
import pandas as pd

#Load datastets
sales_df = pd.read_csv(files["Sales"])
inventory_df = pd.read_csv(files["Inventory"])
products_df = pd.read_csv(files["Products"])
calendar_df = pd.read_csv(files["Calendar"])

print("Datasets loaded successfully.")

# Display datasets shapes
print("\nDataset shapes:")
print(f" - Sales Data: {sales_df.shape}")
print(f" - Inventory Data: {inventory_df.shape}")
print(f" - Products Data: {products_df.shape}")
print(f" - Calendar Data: {calendar_df.shape}")

Datasets loaded successfully.

Dataset shapes:
 - Sales Data: (36550, 6)
 - Inventory Data: (4800, 8)
 - Products Data: (50, 8)
 - Calendar Data: (731, 11)

# Check Datasets Columns

In [20]:
datasets = {
    "Sales": sales_df,
    "Inventory": inventory_df,
    "Products": products_df,
    "Calendar": calendar_df
}

for name, df in datasets.items():
    print("\n" + "=" * 60 )
    print(f"{name} Dataset")
    print("*" * 60)

    print("Columns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

============================================================
Sales Dataset
************************************************************
Columns:
['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion']

First 5 rows:

         Date     SKU  Units_Sold    Revenue    Price  Promotion
0  2024-01-01  SKU001           5   18320.25  3664.05          0
1  2024-01-01  SKU002          15   57085.35  3805.69          0
2  2024-01-01  SKU003           5   40391.15  8078.23          0
3  2024-01-01  SKU004           5   34307.85  6861.57          0
4  2024-01-01  SKU005          12  113918.64  9493.22          0

============================================================
Inventory Dataset
************************************************************
Columns:
['Snapshot_Date', 'SKU', 'Current_Stock', 'On_Order', 'Lead_Time_Days', 'Safety_Stock', 'Reorder_Point', 'Inventory_Value']

First 5 rows:

  Snapshot_Date     SKU  Current_Stock  On_Order  Lead_Time_Days  Safety_Stock  Reorder_Point  Inventory_Value
0    2024-01-01  SKU001             16        23              11             7             18         58420.96
1    2024-01-01  SKU002             29        12               4             5             10        163983.40
2    2024-01-01  SKU003             34        23              14             6             20        209060.22
3    2024-01-01  SKU004             34         4               7             5             12         42257.92
4    2024-01-01  SKU005             23         5               5             6             11        170945.89

============================================================
Products Dataset
************************************************************
Columns:
['SKU', 'Product_Name', 'Category', 'Subcategory', 'Launch_Date', 'Cost_Price', 'Selling_Price', 'Gross_Margin_Per_Unit']

First 5 rows:

      SKU Product_Name    Category Subcategory Launch_Date  Cost_Price  Selling_Price  Gross_Margin_Per_Unit
0  SKU001  Product 001   Furniture       Chair  2022-04-09     1758.45        3664.05                1905.60
1  SKU002  Product 002  Home Decor       Table  2024-05-01     3867.09        3805.69                 -61.40
2  SKU003  Product 003     Kitchen     Cushion  2023-12-22      589.48        8078.23                7488.75
3  SKU004  Product 004    Lighting    Cookware  2023-04-28     1445.74        6861.57                5415.83
4  SKU005  Product 005     Storage        Lamp  2023-04-22     5543.63        9493.22                3949.59

============================================================
Calendar Dataset
************************************************************
Columns:
['date', 'year', 'month', 'quarter', 'week', 'day_of_week', 'is_weekend', 'season', 'holiday', 'is_holiday', 'promotion_event']

First 5 rows:

         date  year  month quarter  week day_of_week  is_weekend  season holiday  is_holiday promotion_event
0  2024-01-01  2024      1      Q1     1      Monday           0  Winter     NaN           0             NaN
1  2024-01-02  2024      1      Q1     1     Tuesday           0  Winter     NaN           0             NaN
2  2024-01-03  2024      1      Q1     1   Wednesday           0  Winter     NaN           0             NaN
3  2024-01-04  2024      1      Q1     1    Thursday           0  Winter     NaN           0             NaN
4  2024-01-05  2024      1      Q1     1      Friday           0  Winter     NaN           0             NaN

# Basic Data Quality check

In [22]:
for name, df in datasets.items():
    print("\n" + "=" * 70)
    print(f"{name} Dataset")
    print("=" * 70)

    # Shape
    print(f"\nRows    : {df.shape[0]:,}")
    print(f"Columns : {df.shape[1]}")

    # Data types
    print("\nData Types:")
    print(df.dtypes)

    # Missing values
    print("\nMissing Values:")
    missing = df.isnull().sum()
    
    if missing.sum() == 0:
        print("✅ No missing values")
    else:
        print(missing[missing > 0])

    # Duplicate rows
    duplicates = df.duplicated().sum()
    print(f"\nDuplicate Rows: {duplicates:,}")

======================================================================
Sales Dataset
======================================================================

Rows    : 36,550
Columns : 6

Data Types:
Date              str
SKU               str
Units_Sold      int64
Revenue       float64
Price         float64
Promotion       int64
dtype: object

Missing Values:
✅ No missing values

Duplicate Rows: 0

======================================================================
Inventory Dataset
======================================================================

Rows    : 4,800
Columns : 8

Data Types:
Snapshot_Date          str
SKU                    str
Current_Stock        int64
On_Order             int64
Lead_Time_Days       int64
Safety_Stock         int64
Reorder_Point        int64
Inventory_Value    float64
dtype: object

Missing Values:
✅ No missing values

Duplicate Rows: 0

======================================================================
Products Dataset
======================================================================

Rows    : 50
Columns : 8

Data Types:
SKU                          str
Product_Name                 str
Category                     str
Subcategory                  str
Launch_Date                  str
Cost_Price               float64
Selling_Price            float64
Gross_Margin_Per_Unit    float64
dtype: object

Missing Values:
✅ No missing values

Duplicate Rows: 0

======================================================================
Calendar Dataset
======================================================================

Rows    : 731
Columns : 11

Data Types:
date                 str
year               int64
month              int64
quarter              str
week               int64
day_of_week          str
is_weekend         int64
season               str
holiday              str
is_holiday         int64
promotion_event      str
dtype: object

Missing Values:
holiday            723
promotion_event    656
dtype: int64

Duplicate Rows: 0

# Converts Date columns

In [25]:

sales_df["Date"] = pd.to_datetime(sales_df["Date"], errors="coerce")
inventory_df["Snapshot_Date"] = pd.to_datetime(
    inventory_df["Snapshot_Date"], 
    errors="coerce"
)
products_df["Launch_Date"] = pd.to_datetime(
    products_df["Launch_Date"], 
    errors="coerce"
)
calendar_df["date"] = pd.to_datetime(
    calendar_df["date"], 
    errors="coerce"
)

print("✅ Date columns converted successfully.")

print("\nDate ranges:")

print(
    "Sales:",
    sales_df["Date"].min(),
    "→",
    sales_df["Date"].max()
)

print(
    "Inventory:",
    inventory_df["Snapshot_Date"].min(),
    "→",
    inventory_df["Snapshot_Date"].max()
)

print(
    "Products:",
    products_df["Launch_Date"].min(),
    "→",
    products_df["Launch_Date"].max()
)

print(
    "Calendar:",
    calendar_df["date"].min(),
    "→",
    calendar_df["date"].max()
)

✅ Date columns converted successfully.

Date ranges:
Sales: 2024-01-01 00:00:00 → 2025-12-31 00:00:00
Inventory: 2024-01-01 00:00:00 → 2025-12-01 00:00:00
Products: 2022-03-12 00:00:00 → 2024-12-09 00:00:00
Calendar: 2024-01-01 00:00:00 → 2025-12-31 00:00:00

# Check SKU Relationships

In [26]:
sales_skus = set(sales_df["SKU"].dropna().unique())
inventory_skus = set(inventory_df["SKU"].dropna().unique())
products_skus = set(products_df["SKU"].dropna().unique())

print("SKU Counts")
print("-" * 40)

print(f"Sales SKUs     : {len(sales_skus):,}")
print(f"Inventory SKUs : {len(inventory_skus):,}")
print(f"Product SKUs   : {len(products_skus):,}")

print("\nSKU Consistency")
print("-" * 40)

print(
    "Sales → Products:",
    len(sales_skus - products_skus),
    "SKUs missing in Products"
)

print(
    "Sales → Inventory:",
    len(sales_skus - inventory_skus),
    "SKUs missing in Inventory"
)

print(
    "Products → Sales:",
    len(products_skus - sales_skus),
    "SKUs with no sales"
)

SKU Counts
----------------------------------------
Sales SKUs     : 50
Inventory SKUs : 200
Product SKUs   : 50

SKU Consistency
----------------------------------------
Sales → Products: 0 SKUs missing in Products
Sales → Inventory: 0 SKUs missing in Inventory
Products → Sales: 0 SKUs with no sales

# Quick Dataset preview

In [28]:
print("SALES")
display(sales_df.head())

print("\nINVENTORY")
display(inventory_df.head())

print("\nPRODUCT MASTER")
display(products_df.head())

print("\nCALENDAR")
display(calendar_df.head())

SALES

        Date     SKU  Units_Sold    Revenue    Price  Promotion
0 2024-01-01  SKU001           5   18320.25  3664.05          0
1 2024-01-01  SKU002          15   57085.35  3805.69          0
2 2024-01-01  SKU003           5   40391.15  8078.23          0
3 2024-01-01  SKU004           5   34307.85  6861.57          0
4 2024-01-01  SKU005          12  113918.64  9493.22          0

INVENTORY

  Snapshot_Date     SKU  Current_Stock  On_Order  Lead_Time_Days  Safety_Stock  Reorder_Point  Inventory_Value
0    2024-01-01  SKU001             16        23              11             7             18         58420.96
1    2024-01-01  SKU002             29        12               4             5             10        163983.40
2    2024-01-01  SKU003             34        23              14             6             20        209060.22
3    2024-01-01  SKU004             34         4               7             5             12         42257.92
4    2024-01-01  SKU005             23         5               5             6             11        170945.89

PRODUCT MASTER

      SKU Product_Name    Category Subcategory Launch_Date  Cost_Price  Selling_Price  Gross_Margin_Per_Unit
0  SKU001  Product 001   Furniture       Chair  2022-04-09     1758.45        3664.05                1905.60
1  SKU002  Product 002  Home Decor       Table  2024-05-01     3867.09        3805.69                 -61.40
2  SKU003  Product 003     Kitchen     Cushion  2023-12-22      589.48        8078.23                7488.75
3  SKU004  Product 004    Lighting    Cookware  2023-04-28     1445.74        6861.57                5415.83
4  SKU005  Product 005     Storage        Lamp  2023-04-22     5543.63        9493.22                3949.59

CALENDAR

        date  year  month quarter  week day_of_week  is_weekend  season holiday  is_holiday promotion_event
0 2024-01-01  2024      1      Q1     1      Monday           0  Winter     NaN           0             NaN
1 2024-01-02  2024      1      Q1     1     Tuesday           0  Winter     NaN           0             NaN
2 2024-01-03  2024      1      Q1     1   Wednesday           0  Winter     NaN           0             NaN
3 2024-01-04  2024      1      Q1     1    Thursday           0  Winter     NaN           0             NaN
4 2024-01-05  2024      1      Q1     1      Friday           0  Winter     NaN           0             NaN

# Calendar missing values analysis

In [29]:
print("=" * 70)
print("HOLIDAY VALUES")
print("=" * 70)

print(calendar_df["holiday"].value_counts(dropna=False))

print("\n" + "=" * 70)
print("PROMOTION EVENT VALUES")
print("=" * 70)

print(calendar_df["promotion_event"].value_counts(dropna=False))

print("\n" + "=" * 70)
print("MISSING HOLIDAY EXAMPLES")
print("=" * 70)

display(
    calendar_df[calendar_df["holiday"].isna()].head(10)
)

print("\n" + "=" * 70)
print("MISSING PROMOTION EVENT EXAMPLES")
print("=" * 70)

display(
    calendar_df[calendar_df["promotion_event"].isna()].head(10)
)

======================================================================
HOLIDAY VALUES
======================================================================
holiday
NaN                 723
Republic Day          2
Independence Day      2
Diwali                2
Christmas             2
Name: count, dtype: int64

======================================================================
PROMOTION EVENT VALUES
======================================================================
promotion_event
NaN                   656
Seasonal Promotion     75
Name: count, dtype: int64

======================================================================
MISSING HOLIDAY EXAMPLES
======================================================================

        date  year  month quarter  week day_of_week  is_weekend  season holiday  is_holiday promotion_event
0 2024-01-01  2024      1      Q1     1      Monday           0  Winter     NaN           0             NaN
1 2024-01-02  2024      1      Q1     1     Tuesday           0  Winter     NaN           0             NaN
2 2024-01-03  2024      1      Q1     1   Wednesday           0  Winter     NaN           0             NaN
3 2024-01-04  2024      1      Q1     1    Thursday           0  Winter     NaN           0             NaN
4 2024-01-05  2024      1      Q1     1      Friday           0  Winter     NaN           0             NaN
5 2024-01-06  2024      1      Q1     1    Saturday           1  Winter     NaN           0             NaN
6 2024-01-07  2024      1      Q1     1      Sunday           1  Winter     NaN           0             NaN
7 2024-01-08  2024      1      Q1     2      Monday           0  Winter     NaN           0             NaN
8 2024-01-09  2024      1      Q1     2     Tuesday           0  Winter     NaN           0             NaN
9 2024-01-10  2024      1      Q1     2   Wednesday           0  Winter     NaN           0             NaN

======================================================================
MISSING PROMOTION EVENT EXAMPLES
======================================================================

        date  year  month quarter  week day_of_week  is_weekend  season holiday  is_holiday promotion_event
0 2024-01-01  2024      1      Q1     1      Monday           0  Winter     NaN           0             NaN
1 2024-01-02  2024      1      Q1     1     Tuesday           0  Winter     NaN           0             NaN
2 2024-01-03  2024      1      Q1     1   Wednesday           0  Winter     NaN           0             NaN
3 2024-01-04  2024      1      Q1     1    Thursday           0  Winter     NaN           0             NaN
4 2024-01-05  2024      1      Q1     1      Friday           0  Winter     NaN           0             NaN
5 2024-01-06  2024      1      Q1     1    Saturday           1  Winter     NaN           0             NaN
6 2024-01-07  2024      1      Q1     1      Sunday           1  Winter     NaN           0             NaN
7 2024-01-08  2024      1      Q1     2      Monday           0  Winter     NaN           0             NaN
8 2024-01-09  2024      1      Q1     2     Tuesday           0  Winter     NaN           0             NaN
9 2024-01-10  2024      1      Q1     2   Wednesday           0  Winter     NaN           0             NaN

# Overall Dataset

In [31]:
summary = pd.DataFrame({
    "Dataset": ["Sales", "Inventory", "Products", "Calendar"],
    "Rows": [
        len(sales_df),
        len(inventory_df),
        len(products_df),
        len(calendar_df)
    ],
    "Columns": [
        sales_df.shape[1],
        inventory_df.shape[1],
        products_df.shape[1],
        calendar_df.shape[1]
    ],
    "Missing Values": [
        sales_df.isna().sum().sum(),
        inventory_df.isna().sum().sum(),
        products_df.isna().sum().sum(),
        calendar_df.isna().sum().sum()
    ],
    "Duplicate Rows": [
        sales_df.duplicated().sum(),
        inventory_df.duplicated().sum(),
        products_df.duplicated().sum(),
        calendar_df.duplicated().sum()
    ]
})

display(summary)

     Dataset   Rows  Columns  Missing Values  Duplicate Rows
0      Sales  36550        6               0               0
1  Inventory   4800        8               0               0
2   Products     50        8               0               0
3   Calendar    731       11            1379               0